version: 2
registries:
  gradle-github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/Alexandre-Carbenay/library
    token: ${{secrets.GH_PACKAGES}}
updates:
  - package-ecosystem: gradle
    directory: /catalog
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /referencing
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /website
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
