server.http2.enabled: true

spring:
  application:
    name: catalog
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_ABSENT

management:
  endpoints:
    web:
      base-path: /management
      exposure.include: '*'
  endpoint:
    health:
      show-details: always
  health:
    probes.enabled: true
    diskspace.enabled: false
    livenessstate.enabled: true
    readinessstate.enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api/doc
  swagger-ui:
    url: /openapi.yml

org.adhuc.library:
  support:
    rest.validation.jsr303:
      enabled: true

logging:
  level:
    org.adhuc.library.referencing: INFO
    com.atlassian.oai.validator.springmvc: WARN
    org.springframework:
      boot:
        autoconfigure.logging: ERROR
        actuate: ERROR
